services:
  be:
    image: kolsherut_be:0.0.0
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - ORIGIN=*
      - ENV=dev
      - PORT=3000
      - ELASTIC_URL=https://srm-staging-elasticsearch.whiletrue.industries
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=ChangeMePlz
      - ELASTIC_RECONNECT_TIMEOUT=5
      - VERBOSE=true
      - LOG_TO_FILE=true
      - LOG_DURATION=10
    volumes:
      - ./volumes/be/logs:/app/logs
  fe:
    image: kolsherut_fe:0.0.0
    restart: unless-stopped
    ports:
      - 5173:80
    volumes:
      - ./volumes/fe/config.json:/usr/share/nginx/html/config.json
      - ./volumes/fe/strings.json:/usr/share/nginx/html/strings.json
      - ./volumes/fe/responseColors.json:/usr/share/nginx/html/responseColors.json
      - ./volumes/fe/filters.json:/usr/share/nginx/html/filters.json
      - ./volumes/fe/homepage.json:/usr/share/nginx/html/homepage.json
      - ./volumes/fe/sitemap.txt:/usr/share/nginx/html/sitemap.txt
    depends_on:
      - be
