services:
  be:
    image: kolsherut_be:0.0.0
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - ORIGIN=*
      - ENV=dev
      - PORT=3000
      - ELASTIC_URL=https://srm-staging-elasticsearch.whiletrue.industries
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=ChangeMePlz
      - ELASTIC_RECONNECT_TIMEOUT=5
      - VERBOSE=true
      - LOG_TO_FILE=true
      - LOG_DURATION=10
      - SEARCHCARDS_FIRST_LENGTH=50
    volumes:
      - ./volumes/be/logs:/app/logs
  fe:
    image: kolsherut_fe:0.0.0
    restart: unless-stopped
    ports:
      - 5173:80
    volumes:
      - ./volumes/fe/configs/config.json:/usr/share/nginx/html/configs/config.json
      - ./volumes/fe/configs/strings.json:/usr/share/nginx/html/configs/strings.json
      - ./volumes/fe/configs/responseColors.json:/usr/share/nginx/html/configs/responseColors.json
      - ./volumes/fe/configs/filters.json:/usr/share/nginx/html/configs/filters.json
      - ./volumes/fe/configs/homepage.json:/usr/share/nginx/html/configs/homepage.json
      - ./volumes/fe/configs/GUISiteMap.json:/usr/share/nginx/html/configs/GUISiteMap.json
      - ./volumes/fe/configs/linksBelow.json:/usr/share/nginx/html/configs/linksBelow.json
      - ./volumes/fe/configs/modules.json:/usr/share/nginx/html/configs/modules.json
      - ./volumes/fe/configs/metaTags.json:/usr/share/nginx/html/configs/metaTags.json
      - ./volumes/fe/sitemap.txt:/usr/share/nginx/html/sitemap.txt
    depends_on:
      - be
