FROM nginx
COPY dist /usr/share/nginx/html
COPY dist/config.json /usr/share/nginx/html/dev-config.json
COPY dist/strings.json /usr/share/nginx/html/dev-strings.json
COPY nginx.conf /etc/nginx/nginx.conf
