name: BE CI (staging)
# Builds BE on any branch when be/ changes. Deploys (staging) only on main.
on:
  push:
    branches:
      - '**'
    paths:
      - 'be/**'
      - '.github/workflows/be-ci.yml'

permissions:
  contents: write
  packages: write

concurrency:
  group: be-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: be/package-lock.json

      - name: Install & Build
        working-directory: be
        run: |
          npm ci
          npm run build

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Build
        working-directory: be
        env:
          IMAGE_NAME: kol-sherut-be
        run: |
          BUILD_ARGS=""
          if docker pull ghcr.io/kolzchut/${IMAGE_NAME}:latest; then
            BUILD_ARGS="--cache-from ghcr.io/kolzchut/${IMAGE_NAME}:latest"
          fi
          docker build -t be-build $BUILD_ARGS .

      - name: Push & Update Helm (staging)
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE_NAME: kol-sherut-be
          CHART_NAME: etl
          CHART_SUBPART: api
          SRM_DEVOPS_DEPLOY_KEY: ${{ secrets.SRM_DEVOPS_DEPLOY_KEY }}
        run: |
          IMAGE_SHA="ghcr.io/kolzchut/${IMAGE_NAME}:${GITHUB_SHA}"
          docker tag be-build "$IMAGE_SHA"
          docker push "$IMAGE_SHA"
          docker tag be-build ghcr.io/kolzchut/${IMAGE_NAME}:latest
          docker push ghcr.io/kolzchut/${IMAGE_NAME}:latest
          # write SSH key safely (preserve newlines, strip CR)
          printf "%s" "$SRM_DEVOPS_DEPLOY_KEY" | tr -d '\r' > srm_devops_deploy_key
          chmod 400 srm_devops_deploy_key
          export GIT_SSH_COMMAND="ssh -i $(pwd)/srm_devops_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          git clone git@github.com:kolzchut/srm-devops.git
          git config --global user.name "srm-devops CI"
          git config --global user.email "srm-devops-ci@localhost"
          cd srm-devops
          VALUES_FILE="helm/${CHART_NAME}/values.auto-updated.yaml"
          echo "Updating $VALUES_FILE with image: $IMAGE_SHA"
          echo "Before (image lines):" && (grep -n 'image:' "$VALUES_FILE" || true)
          bin/update_yaml.py '{"'"${CHART_SUBPART}"'":{"image":"'"${IMAGE_SHA}"'"}}' "$VALUES_FILE"
          echo "After  (image lines):" && (grep -n 'image:' "$VALUES_FILE" || true)
          echo "Git diff for $VALUES_FILE (if any):" && (git diff -- "$VALUES_FILE" || true)
          git add "$VALUES_FILE"
          git commit -m "BE staging image update: $VALUES_FILE" || echo "No changes to commit"
          git push origin main
