apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "backend.fullname" . }}-elasticsearch
  labels:
    app: elasticsearch
    {{- include "backend.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "backend.fullname" . }}-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 10 }}
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "true"
        # We explicitly disable HTTP SSL to ensure it matches our http probe and backend config
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms4g -Xmx4g"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secrets
              key: ELASTIC_PASS
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - |
              # CHANGE IS HERE: Changed https -> http
              curl -s -k -u "elastic:$ELASTIC_PASSWORD" http://localhost:9200/_cluster/health | grep -q 'status.*\(green\|yellow\)'
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.elasticsearch.volumeClaim.storageClass }}
      resources:
        requests:
          storage: {{ .Values.elasticsearch.volumeClaim.size }}