apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-elasticsearch
  labels:
    app: elasticsearch
    {{- include "backend.labels" . | nindent 4 }}
spec:
  ports:
  - port: 9200
    name: http
    targetPort: 9200
  selector:
    app: elasticsearch