{{- if .Values.frontend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frontend.configClaimName" . }}
  labels:
    component: frontend
    {{- include "backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: {{ include "frontend.configVolumeName" . }}
  resources:
    requests:
      storage: {{ .Values.frontend.persistence.size | quote }}
{{- end }}
